website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from . import db
from .models import User
from flask_login import login_required, current_user, login_user, logout_user
import re
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

# logs in user if user exists, username and password are correct
@auth.route('/login', methods = ['GET', 'POST'])
def login():
    #print('in the login method')
    if request.method == 'POST':
        print('method is post')
        username = request.form.get('username')
        password = request.form.get('password')
        #print(username)
        print(password)
        user = User.query.filter_by(username = username).first()
        #print(user)
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember = True)
                user.current_score = 0
                db.session.commit()
                return redirect(url_for('views.game', level='level1', fileNum=1))
            else:
                flash("Password is incorrect")
        else:
            flash("User does not exist")
    
    return render_template("login.html", user=current_user, active_page='login')


#logs out the user and returns to login page
@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))



#creates a new user if the requirements are met
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    #pull infro from request form
    if request.method == 'POST':
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        #print block for testing
        print('username: ' + username)
        print('password1: ' + password1)
        print('password2: ' + password2)

        #search for username
        user = User.query.filter_by(username=username).first()
        regexp = re.compile('[^0-9za-zA-Z]+')
        #if there is already a user w/ this username, alert the user to choose
        # a differet name.
        if user:
            return "This username is already taken"

        #check password validity
        #do the passwords match
        elif password1 != password2:
            return "Passwords must match"
        #is the password longer than 6 chars
        elif len(password1) < 7:
            return "Password must be at least 7 chatacter long"
        #does the password include a captial letter
        elif password1.islower():
            return 'Password must contain at least 1 captial letter'
        #does the password include a numner or special character
        elif not re.search('[0-9]', password1) and not regexp.search(password):
            return 'Password must contain at least 1 number or special character'
        else: # if all tests pass then create the user
            new_user = User(username=username, password=generate_password_hash(password1),highscore=0, current_score=0)
            db.session.add(new_user)
            db.session.commit()
            print('User Created!')
            return redirect(url_for('auth.login'))
    
    return render_template('signup.html', user=current_user, active_page = 'signup')




        

website/templates/game.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>neatCode - gameplay</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Custom CSS -->
    <!-- Flask -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/game-stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main-stylesheet.css') }}">  
    
    <!-- Modules -->
    <!-- codeflask -->
    <script src="{{ url_for('static', filename='node_modules/codeflask/build/codeflask.min.js')}}"></script>
    
    <!-- prism -->
    <script src="{{ url_for('static', filename='node_modules/prismjs/prism.js')}}"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    
    <!--
    <script type="text/javascript" src="{{url_for('static', filename='node_modules/highlight-within-textarea/jquery.highlight-within-textarea.js')}}"></script>
    <script src="{{url_for('static', filename = 'node_modules/tipso/src/tipso.js')}}"></script>
    -->
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">neatCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.game',level='level1',fileNum='1')}}">Play</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
		 <li class="nav-item">
		   <a class="nav-link" href="/levelselect">Level-Select</a>
	      </li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout {{ user.username }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/login">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signup">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    <!-- Main Body -->
    <main>

      <!-- Main container -->
      <div class="container-fluid">
	  {% with msg=get_flashed_messages()%}
             {% if msg %}
                   {% for m in msg %}
                      <h4>{{ m }}</h4>
                   {% endfor %}
             {% endif %}
        {% endwith %}
        <div class="row" id="game">
          <div class="col-md-9">
            <!-- CodeFlask -->
            <!-- flask div -->
            <div class="code-editor" id='codeflask'>
			{% for line in code %}
		   	{{line}}
			<br>
			{% endfor %}
            </div>
            <!-- flaskcode script -->
            <script>
		   import CodeFlask from 'codeflask';
              const editorElem = document.getElementById('codeflask');
              const flask = new CodeFlask(editorElem, {language: 'js', lineNumbers: true, readonly:true});
            </script>
          </div>
          <div class="col-md-3">
		<div class="bg-secondary text-white p-3">
		  <a class="nav-link" style="color:white;" href="#" > Instructions</a>
		 </div>
		<br>
		<form method='POST'>
            <div class="bg-secondary text-white p-3">
             <label for="answer">Your Guess:</label>
		  <input type="text" class="form-control" id="answer" name="answer" placeholder="Enter here"
            </div>
		</form>
		<br>
		<div class="bg-secondary text-white p-3">
			<p>Similarty Score: 
				<br>
			 	{{similarity}}
			</p>
		</div>
		<div class="bg-secondary text-green p-3">
			<p> Current Score:
			<br>
			{{user.current_score}}
			</p>
		   {% if next_file != '0' %}
			<a href="{{url_for('views.game',level=curr_level,fileNum=next_file)}}" class='next'>Next Example &raquo</a>
		   {% else %}
			<p> This is the last example in this level.</p>
		   {% endif %}
		</div>
          </div>
        </div>
      </div>
    </main>

    <!-- footer -->
    <footer class="py-3">
      <div class="container-fluid text-center">
        <p> 2023 neatCode</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>neatCode - Develop Your Programming Skills</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <!-- Flask -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/homepage-stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main-stylesheet.css') }}">
    <!-- HTML -->
	  <link rel="stylesheet" href="./static/CSS/homepage-stylesheet.css">
    <link rel="stylesheet" href="./static/CSS/main-stylesheet.css">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">neatCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.game',level='level1',fileNum='1')}}">Play</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
		 <li class "nav-item">
		   <a class="nav-link" href="/levelselect">Level-Select</a>
		 </li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout {{ user.username }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/login">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signup">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    

    <!-- Main Body -->
    <main>
      <!-- Jumbotron -->
      <section class="jumbotron">
        <h1 class="display-4">Improve Your Programming Skills</h1>
        <p class="lead">neatCode is a fun and engaging way to practice programming and improve your skills.</p>
        <hr class="my-4">
        <a class="btn btn-lg" href="{{url_for('views.game', level='level1',fileNum='1')}}" role="button" id="play-btn">Play Now</a>
      </section>

      <!-- group of cards -->
      <section class="container-fluid" style="width:fit-content; padding-bottom: 32px;">
        <div class="row">
          <div class="col-sm-4">
            <!-- card 1 -->
            <div class="card">
              <img class="card-img-top" src="https://images.pexels.com/photos/943096/pexels-photo-943096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="coding image">
              <div class="card-body">
                <h5 class="card-title">Challenging Programming Puzzles</h5>
                <p class="card-text">neatCode provides a variety of programming puzzles that will help you develop and test your programming skills.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <!-- card 2 -->
            <div class="card">
              <img class="card-img-top" src="https://images.unsplash.com/photo-1533237264985-ee62f6d342bb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2338&q=80" alt="leaderboard image">
              <div class="card-body">
                <h5 class="card-title">Compete on the Leaderboard</h5>
                <p class="card-text">neatCode allows you to compete with other players and climb the leaderboard.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-4">
            <!-- card 3 -->
            <div class="card">
              <img class="card-img-top" src="https://images.unsplash.com/photo-1598271313575-f0ccfdddea7d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80" alt="badges image">
              <div class="card-body">
                <h5 class="card-title">Earn Badges</h5>
                <p class="card-text">neatCode offers badges that you can earn as you progress and master programming concepts.</p>
              </div>
            </div>
          </div>
        </div>
    </main>

    <footer class="py-3">
      <div class="container-fluid text-center">
        <p>2023 neatCode</p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/leaderboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>neatCode - Leaderboard</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <!-- Flask -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/leaderboard-stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main-stylesheet.css') }}">
    <!-- HTML -->
	  <link rel="stylesheet" href="./static/CSS/leaderboard-stylesheet.css">
    <link rel="stylesheet" href="./static/CSS/main-stylesheet.css">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="/">neatCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.game',level='level1', fileNum='1')}}">Play</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
	       <li class="nav-item">
		   <a class="nav-link" href="levelselect.html">Level-Select</a>
		 </li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="/logout">Logout {{ user.username }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/login">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/signup">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>

    <!-- Main Body -->
    <main class="container-fluid">
      <h1 class="text-center mb-4">neatCode Leaderboard</h1>
      <table class="table table-striped table-dark">
        <thead>
          <tr>
            <th scope="col">Rank</th>
            <th scope="col">Username</th>
            <th scope="col">Score</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>user123</td>
            <td>100</td>
            <td>April 1, 2023</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>programmer27</td>
            <td>85</td>
            <td>April 2, 2023</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>neatCoder</td>
            <td>75</td>
            <td>April 3, 2023</td>
          </tr>
        </tbody>
      </table>
    </main>

    <!-- footer -->
    <footer class="py-3">
      <div class="container-fluid text-center">
        <p>2023 neatCode</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/levelselect.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>neatCode - Level Select</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <!-- Flask -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login-stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main-stylesheet.css') }}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="#">neatCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="home.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.game',level='level1', fileNum='1')}}">Play</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="leaderboard.html">Leaderboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
		 <li>
		    <a class="nav-link" href="levelselect.html">Level-Select</a>
		 </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Main Body -->
    <main>
      <!-- Main container -->
      <div class="container-fluid">
	 
        <h1 class="text-center mb-4">Level Select</h1>
        <a class="nav-link" href="{{url_for('views.game',level='level1',fileNum='1')}}"> Level 1 </a>
	   <a class="nav-link" href="{{url_for('views.game',level='level2',fileNum='1')}}"> Level 2 </a>
	   <a class="nav-link" href="{{url_for('views.game',level='level3',fileNum='1')}}"> Level 3 </a>
		
    </main>

    <!-- footer -->
    <footer class="py-3">
      <div class="container-fluid text-center">
        <p>2023 neatCode</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>neatCode - Sign In</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Custom CSS -->
    <!-- Flask -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login-stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main-stylesheet.css') }}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
  </head>
  <body>
    <!-- Navbar -->
    <header>
      <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="#">neatCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link" href="home.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.game',level='level1', fileNum='1')}}">Play</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="leaderboard.html">Leaderboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
		 <li class="nav-item">
		   <a class="nav-link" href="levelselect.html">Level-Select</a>
		 </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Main Body -->
    <main>
      <!-- Main container -->
      <div class="container-fluid">
	 {% with msg=get_flashed_messages()%}
             {% if msg %}
                   {% for m in msg %}
                      <h4>{{ m }}</h4>
                   {% endfor %}
             {% endif %}
        {% endwith %}
        <h1 class="text-center mb-4">Sign In</h1>
        <form method='POST'>
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
          </div>
          <button type="submit" class="btn btn-block" id="sign-in-btn">Sign In</button>
        </form>
	  <div class='container'>
		<a class="nav-link" href="{{url_for('auth.signup')}}">No Account? Sign up here!</a>
	  </div>
    </main>

    <!-- footer -->
    <footer class="py-3">
      <div class="container-fluid text-center">
        <p>2023 neatCode</p>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>